name: Deploy To Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'UnitTestWorkshop Debug build to distribute on Firebase app distribution'
        description: 'Release Notes'


jobs:
    build:
      name: Building and distributing app
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: build debug
          run: ./gradlew assembleDebug
        - name: upload artifact to Firebase App Distribution
          uses: wzieba/Firebase-Distribution-Github-Action@v1
          with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
            groups: my-tester
            file: app/build/intermediates/apk/debug/app-debug.apk
            releaseNotes: ${{inputs.release_notes}}