name: Deploy To Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'UnitTestWorkshop Debug build to distribute on Firebase app distribution'
        description: 'Release Notes'
      version_name:
        type: number
        required: true
        default: 1.0
        description: 'Version Name (e.g., 1.0)'


jobs:
    build:
      name: Building and distributing app on Debug variant
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Make gradlew executable
          run: chmod +x ./gradlew

        - name: Increment versionCode
          id: increment_version_code
          run: |
           INCREMENTED_VERSION_CODE=$(( ${{ secrets.VERSION_CODE_COUNTER }} + 1 ))
            echo "INCREMENTED_VERSION_CODE=$INCREMENTED_VERSION_CODE" >> $GITHUB_ENV
            echo "The incremented versionCode is=${{ env.INCREMENTED_VERSION_CODE }}"

        - name: Execute Gradle command - clean and assembleDebug with Version Info
          run: ./gradlew clean assembleDebug -PversionCode=${{ env.INCREMENTED_VERSION_CODE }} -PversionName="${{ inputs.version_name }}"

        - name: Execute Gradle command - assembleDebug
          run: ./gradlew assembleDebug

        - name: upload artifact to Firebase App Distribution
          uses: wzieba/Firebase-Distribution-Github-Action@v1
          with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
            groups: my-tester
            file: app/build/outputs/apk/debug/app-debug.apk
            releaseNotes: ${{inputs.release_notes}}
